apiVersion: v1
kind: Service
metadata:
  name: basmatinet-app
  labels:
    app: basmatinet-app
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: basmatinet-app
