name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Set up virtual environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8.12
        environment-file: conda-env.yaml
    - name: Activate the test environment
      run: conda activate test
      shell: bash -l {0}
    - name: Unit tests with pytest
      run: make unit-tests
      shell: bash -l {0}
    - name: Integration tests
      run: make integration-tests
      shell: bash -l {0}
    - name: Build Docker Image
      run: make build && make run
      shell: bash -l {0}
    - name: Make a prediction to see if everything is working.
      run:  make predict
      shell: bash -l {0}
